#To run, "snakemake -core 1 --slurm --use -conda --jobs 1"
#Dr. Bradley notes - 4 hrs jobs to 50

#Make Global Wildcards
(smp,read)= glob_wildcards("/fs/project/bradley.720/users/dicesare.14/Raw/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_{F}.fastq.gz")

rule all:
    input:
        expand("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_{F}.fastq.gz",
            ERR=smp,
            F=read),
        expand("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/abund/{ERR}.bracken", ERR=smp),
        expand("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas/{ERR}/species/species_profile.tsv", ERR=smp),
        expand("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas2/{ERR}/species/species_profile.tsv", ERR=smp),
        expand("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/sample_manifest.tsv", ERR=smp),
        directory("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas2/merged/")

rule fastP:
    input: 
        in1="/fs/project/bradley.720/users/dicesare.14/Raw/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_1.fastq.gz",
        in2="/fs/project/bradley.720/users/dicesare.14/Raw/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_2.fastq.gz",
    output: 
        out1="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_1.fastq.gz",
        out2="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_2.fastq.gz",
    threads: 16
    conda: "../envs/env.yml"
    shell:
        "fastp -i {input.in1} -I {input.in2} -o {output.out1} -O {output.out2} -w {threads}"

rule kraken:
    input:
        in1 = "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_1.fastq.gz",
        in2 = "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_2.fastq.gz"
    output:
        out = "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/abund/{ERR}.kraken2",
        report = "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/abund/{ERR}.kreport"
    threads: 40
    conda: "../envs/env.yml"
    shell:
        "kraken2 --db /fs/project/bradley.720/db/krakenB/minikraken2_v1_8GB "
        "--threads {threads} "
        "--output {output.out} "
        "--report {output.report} "
        "--paired "
        "{input.in1} {input.in2} "

rule bracken:
    input:
        "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/abund/{ERR}.kreport",
    output:
        "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/abund/{ERR}.bracken",
    conda: "../envs/env.yml"
    shell:
        "bracken -d /fs/project/bradley.720/db/krakenB/minikraken2_v1_8GB "
        "-i {input} "
        "-o {output} "
        "-r 100 "
        "-l S"

rule midas:
    input:
        r1="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_1.fastq.gz",
        r2="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_2.fastq.gz"
    output: "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas/{ERR}/species/species_profile.tsv"
    conda: "../envs/midas.yml"
    params:
        name="{ERR}"
    threads: 40 
    shell:
        "run_midas.py species "
        "-1 {input.r1} "
        "-2 {input.r2} "
        "-d /fs/project/bradley.720/db/MIDAS/midas_db_v1.2/ "
        "-t {threads} "
        "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas/v1/{params.name}/"

rule midas2:
    input:
        r1="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_1.fastq.gz",
        r2="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/trimmed/{ERR}_Illumina_HiSeq_2000_paired_end_sequencing_marine_metagenome_Illumina_F_2.fastq.gz"
    output: "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas2/{ERR}/species/species_profile.tsv"
    conda: "../envs/midas2.yml"
    params:
        name="{ERR}"
    threads: 40
    shell:
        "midas2 run_species --sample_name {params.name} "
        "-1 {input.r1} "
        "-2 {input.r2} "
        "--midasdb_dir /fs/project/bradley.720/db/MIDAS/midas_db_v1.2/ "
        "-t {threads} "
        "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas/v2/{params.name}/"

rule midas2_sample_manifest:
    output: "/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/sample_manifest.tsv"
    run:
        with(open(output[0], 'w')) as fh:
            fh.write("sample_name\tmidas_outdir\n")
            for s in smp:
                fh.write(f"{s}\tdata/processed/midas_coverage/\n")

rule midas2_combine:
    input:
        sm="/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/sample_manifest.tsv"
    output: directory("/fs/project/bradley.720/users/kananen.13/phylogenize/test/taraOceans/midas2/merged/")
    conda: "../envs/midas2.yml"
    shell:
        "midas2 merge_species "
        "--samples_list {input.sm} "
        "--min_cov 2 {output}"
