description: RNAseq schema that allows for bacterial paired end read quantification. 
imports:
  - http:/schema.databio.org/pep/2.0.0.yaml
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        project:
          type: string
          description: "Project Identifier For The Sample"
        sample_name: 
          type: string
          description: "Name Of The Sample"
        genomes:
          anyOf:
            - type: string
              description: "Pangenome .ffn file"
            - type: array
        centroid:
          anyOf:
            - type: string
              description: "centroid information in a text file (see Readme)"
            - type: array
      required_files:
        - genomes
        - centroid
      required:
        - sample_name
        - project
        - organism
        - seq_method
required:
  - samples